// Package gateway_a provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package gateway_a

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for PostPaymentsJSONBodyType.
const (
	Deposit    PostPaymentsJSONBodyType = "deposit"
	Withdrawal PostPaymentsJSONBodyType = "withdrawal"
)

// PostPaymentsJSONBody defines parameters for PostPayments.
type PostPaymentsJSONBody struct {
	Amount        float32                  `json:"amount"`
	Currency      string                   `json:"currency"`
	TransactionId string                   `json:"transactionId"`
	Type          PostPaymentsJSONBodyType `json:"type"`
}

// PostPaymentsJSONBodyType defines parameters for PostPayments.
type PostPaymentsJSONBodyType string

// PostPaymentsJSONRequestBody defines body for PostPayments for application/json ContentType.
type PostPaymentsJSONRequestBody PostPaymentsJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostPaymentsWithBody request with any body
	PostPaymentsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostPayments(ctx context.Context, body PostPaymentsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStatusTransactionId request
	GetStatusTransactionId(ctx context.Context, transactionId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostPaymentsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPaymentsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostPayments(ctx context.Context, body PostPaymentsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostPaymentsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStatusTransactionId(ctx context.Context, transactionId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatusTransactionIdRequest(c.Server, transactionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostPaymentsRequest calls the generic PostPayments builder with application/json body
func NewPostPaymentsRequest(server string, body PostPaymentsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostPaymentsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostPaymentsRequestWithBody generates requests for PostPayments with any type of body
func NewPostPaymentsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/payments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetStatusTransactionIdRequest generates requests for GetStatusTransactionId
func NewGetStatusTransactionIdRequest(server string, transactionId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "transactionId", runtime.ParamLocationPath, transactionId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/status/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostPaymentsWithBodyWithResponse request with any body
	PostPaymentsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPaymentsResponse, error)

	PostPaymentsWithResponse(ctx context.Context, body PostPaymentsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPaymentsResponse, error)

	// GetStatusTransactionIdWithResponse request
	GetStatusTransactionIdWithResponse(ctx context.Context, transactionId string, reqEditors ...RequestEditorFn) (*GetStatusTransactionIdResponse, error)
}

type PostPaymentsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Status        *string `json:"status,omitempty"`
		TransactionId *string `json:"transactionId,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostPaymentsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostPaymentsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStatusTransactionIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Status        *string `json:"status,omitempty"`
		TransactionId *string `json:"transactionId,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetStatusTransactionIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStatusTransactionIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostPaymentsWithBodyWithResponse request with arbitrary body returning *PostPaymentsResponse
func (c *ClientWithResponses) PostPaymentsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostPaymentsResponse, error) {
	rsp, err := c.PostPaymentsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPaymentsResponse(rsp)
}

func (c *ClientWithResponses) PostPaymentsWithResponse(ctx context.Context, body PostPaymentsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostPaymentsResponse, error) {
	rsp, err := c.PostPayments(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostPaymentsResponse(rsp)
}

// GetStatusTransactionIdWithResponse request returning *GetStatusTransactionIdResponse
func (c *ClientWithResponses) GetStatusTransactionIdWithResponse(ctx context.Context, transactionId string, reqEditors ...RequestEditorFn) (*GetStatusTransactionIdResponse, error) {
	rsp, err := c.GetStatusTransactionId(ctx, transactionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStatusTransactionIdResponse(rsp)
}

// ParsePostPaymentsResponse parses an HTTP response from a PostPaymentsWithResponse call
func ParsePostPaymentsResponse(rsp *http.Response) (*PostPaymentsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostPaymentsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status        *string `json:"status,omitempty"`
			TransactionId *string `json:"transactionId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetStatusTransactionIdResponse parses an HTTP response from a GetStatusTransactionIdWithResponse call
func ParseGetStatusTransactionIdResponse(rsp *http.Response) (*GetStatusTransactionIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStatusTransactionIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status        *string `json:"status,omitempty"`
			TransactionId *string `json:"transactionId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
